rem set Java classpath entries for OpenCyc

set OPENCYC_CLASSPATH=..\..\lib\junit.jar
set OPENCYC_CLASSPATH=%OPENCYC_CLASSPATH%;jakarta-oro-2.0.3.jar
set OPENCYC_CLASSPATH=%OPENCYC_CLASSPATH%;commons-collections.jar
set OPENCYC_CLASSPATH=%OPENCYC_CLASSPATH%;xerces.jar
set OPENCYC_CLASSPATH=%OPENCYC_CLASSPATH%;ViolinStrings.jar
set OPENCYC_CLASSPATH=%OPENCYC_CLASSPATH%;jdom.jar
set OPENCYC_CLASSPATH=%OPENCYC_CLASSPATH%;FIPA_OSv2_1_0.jar
set OPENCYC_CLASSPATH=%OPENCYC_CLASSPATH%;jena.jar
set OPENCYC_CLASSPATH=%OPENCYC_CLASSPATH%;rdf-api-2001-01-19.jar
set OPENCYC_CLASSPATH=%OPENCYC_CLASSPATH%;icu4j.jar
set OPENCYC_CLASSPATH=%OPENCYC_CLASSPATH%;dynamicjava.jar

echo %OPENCYC_CLASSPATH%